### PR TITLE
Extended traced_attributes scope to after_request (response) too

### PR DESCRIPTION
**Pull request by lukacsg**
Traced_attributes is given and scanned in _after_request_fn too.
The motivation is that this way the attributes of the response object could be presented in the trace also.
Our goal is to have more control over the traced attributes because our task requires also the input and the output data in one point.

### CODE REVIEW

**Comment by lukacsg** [comment]
Hi!
Could you take a look and push this PR?
This PR would be used to solve in a Seldon issue (https://github.com/SeldonIO/seldon-core/issues/719).
We are waiting this to use it in production so it would be nice if it wolud be in in a next release too.
@carlosalberto  @yurishkuro @Jamim @jan25 

Thanks!

**Comment by Jamim** [comment]
Hello @lukacsg,
Could you please resolve conflicts?
Thank you!

**Comment by lukacsg** [comment]
Hello @Jamim 
I resolved the conflict!

Thank you for working on this PR!

**Comment by lukacsg** [comment]
@Jamim  @carlosalberto 
Hi!
I really welcome that this thread is still alive.
Could you push this PR to master and make a release?
It is vital for us.

Thank you in advance.

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.

**Pull request closed without merging**
