### PR TITLE
Allow to have the app set late for FlaskTracing.

### PR DESCRIPTION
**Pull request by carlosalberto**
Addresses #22

### CODE REVIEW

**Comment by carlosalberto** [comment]
Hey @denisdubovitskiy does this looks fine to you? Does this solve your needs? Let me know ;)

**Comment by denisdubovitskiy** [comment]
@carlosalberto seems better enough ;-). But what if you need to initialize a tracer by configuring it from the app.config (I mean host, port, service name, etc?

**Comment by denisdubovitskiy** [comment]
Init_app approach actually allows you to defer actual object creation/initialization. It means that if I call FlaskTracer() without any args and then pass an app in init_app() - the tracer will be initialized using app.conf vars during app creation, not on any other level. As an example you can see how other useful modules provide such a functionality. To get an idea, I recommend you to look into the sources of FlaskRedis or FlaskSQLAlchemy - most widely used ones

**Comment by carlosalberto** [comment]
I see. I'm going to rename the name to `init_app` to make it more Flask-esque.

About the configuration being taken from `app.conf` I will cook later some another PR, as this would be needed on the base case as well (that is, `Flask(app=app)`, and consume *both* the passed arguments and the ones in `app.conf`, if any).

**Comment by etmitchell** [comment]
Hi there! Is there a timeline for when this will be merged into master? This functionality is definitely super handy!

**Comment by denisdubovitskiy** [comment]
@etmitchell @carlosalberto Yeah! We're also waiting for this PR to be merged!

**Comment by denisdubovitskiy** [comment]
Any changes?

**Comment by tcopple** [comment]
Did this ever get merged? Seems like it passes checks, code is complete, etc.

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.

**Pull request closed without merging**
