### PR TITLE
Allow the underlying tracer initialization to be deferred

### PR DESCRIPTION
**Pull request by kevinjqiu**
For some tracer implementation (like [Jaeger](https://github.com/jaegertracing/jaeger-client-python/issues/60)), the initialization of the tracer should be deferred until the wsgi server forks. We cannot directly create a jaeger tracer instance and pass it to `FlaskTracer` constructor upon startup.

This PR addresses this issue. The underlying tracer initialization can be deferred if we pass a callable as argument to the constructor.

### CODE REVIEW

**Comment by ror6ax** [comment]
Hi, what is the status of it? Project is effectively dead until this is fixed, or is there a way to make it work somehow?

**Comment by ror6ax** [comment]
Ping @kevinjqiu

**Comment by kevinjqiu** [comment]
@ror6ax The project seems to be dead or at least dormant. There hasn't been any new commits for over a year. Issues and PRs are not being tended to... It's unclear who the maintainers are...

I was excited by the prospects of opentracing. Was surprised to see the state of framework integration (or the lack thereof) for the most popular Python web frameworks out there...

To work around it I guess you can run the forked version and upload to your in-house PyPI server (like devpi or something)...

**Comment by ror6ax** [comment]
I'd like to get Opentracing community's blessing and take over maintaining this, if possible. In my use case it's a valuable tool, developing it off-site makes no sense. 

@tedsuo @carlosalberto @dominikh - what do you guys say?

**Comment by yurishkuro** [comment]
@ror6ax you are most welcome to do maintenance on this project. I can help with some guidance, but I'm not really a Flask expert.

**Comment by yurishkuro** [comment]
please rebase off master

**Comment by bhs** [comment]
@ror6ax thank you for the ping!

I am in a state of personal time-bankruptcy and am definitely an inferior maintainer compared with, say, you!  So I will happily add @ror6ax to the owners for this repo, and also for the `pypi` artifact if you can supply your username there.

Please `@bhs` me, as I am passively subscribed to so many github repos that I am unable to follow all of the various discussions amidst an exploding email inbox and a gapless calendar during the work day. :(

**Comment by ror6ax** [comment]
@yurishkuro - I'll wait for your official blessing for this one. 
@bhs - I'm `ror6ax` on pypi as well as here. Thanks!

**Comment by bhs** [comment]
@ror6ax done re pypi – thanks again.

**Pull request merged**
